apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak
  name: keycloak-external
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: keycloak
  sessionAffinity: None
  type: NodePort