apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-jaxrs-app-client-deployment
  labels:
    app: my-jaxrs-app-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-jaxrs-app-client
  template:
    metadata:
      labels:
        app: my-jaxrs-app-client
    spec:
      containers:
        - name: my-jaxrs-app-client
          image: quay.io/tborgato/my-jaxrs-app-client
          ports:
            - containerPort: 8080
            - containerPort: 9990
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9990
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9990
          startupProbe:
            httpGet:
              path: /health/started
              port: 9990
          env:
            - name: SIMPLE_MICROSERVICE_SERVER_URI
              value: "http://my-jaxrs-app-server-service:8080/hello"
