apiVersion: v1
kind: Service
metadata:
  name: simple-microservice-client-service
  labels:
    app: simple-microservice-client
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: simple-microservice-client
  type: NodePort
