apiVersion: v1
kind: Service
metadata:
  name: simple-microservice-server-service
  labels:
    app: simple-microservice-server
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: simple-microservice-server
  type: ClusterIP
