apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-microservice-server-deployment
  labels:
    app: simple-microservice-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-microservice-server
  template:
    metadata:
      labels:
        app: simple-microservice-server
    spec:
      containers:
        - name: simple-microservice-server
          image: quay.io/tborgato/simple-microservice-server
          ports:
            - containerPort: 8080
            - containerPort: 9990
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9990
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9990
          startupProbe:
            httpGet:
              path: /health/started
              port: 9990
