apiVersion: v1
kind: Service
metadata:
  name: artemis-service
  labels:
    app: artemis
spec:
  ports:
    - protocol: TCP
      port: 61616
      targetPort: 61616
      name: artemis-port
    - protocol: TCP
      port: 8161
      targetPort: 8161
      name: artemis-console-port
  selector:
    app: artemis
