apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-jaxrs-app-server2-secured-deployment
  labels:
    app: my-jaxrs-app-server2-secured
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-jaxrs-app-server2-secured
  template:
    metadata:
      labels:
        app: my-jaxrs-app-server2-secured
    spec:
      containers:
        - name: my-jaxrs-app-server2-secured
          image: quay.io/tborgato/my-jaxrs-app-server2-secured
          ports:
            - containerPort: 8080
            - containerPort: 9990
          livenessProbe:
            httpGet:
              path: /health/live
              port: 9990
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 9990
          startupProbe:
            httpGet:
              path: /health/started
              port: 9990
          env:
            - name: MP_JWT_VERIFY_ISSUER
              value: "http://192.168.39.143:30999/realms/myrealm"
            - name: MP_JWT_VERIFY_PUBLICKEY.LOCATION
              value: "http://keycloak-internal:8080/realms/myrealm/protocol/openid-connect/certs"
